### ISSUE TITLE
Custom file not loading

### ISSUE THREAD

**Issue by jben2021** [SpectralSequences/sseq#65]
Tried uploading the following code into web version as a text file and as a JSON file but neither worked:
{
    "p": 2,
    "generic": false,

    "type": "finite dimensional module",
    "gens": {"x0.x0": 0, "x0.x1": 1, "x1.x0": 1, "x1.x1": 2},
    "actions": [
        "Sq1 x0.x0 = x1.x0 + x0.x1",
        "Sq1 x1.x0 = x1.x1",
        "Sq1 x0.x1 = x1.x1",
        "Sq2 x0.x0 = x1.x1"
    ]
}

**Comment by dalcde** [comment]
It works for me. What exactly did you try?

**Comment by jben2021** [comment]
Underneath "Custom" I used the Upload button and selected the JSON version. I set my range to 30, but then the screen went blank. Maybe I need to use a different file type?

**Comment by dalcde** [comment]
The file type should not matter. What browser are you on? Do you see any
error in the console?

**Comment by jben2021** [comment]
https://user-images.githubusercontent.com/86863926/151466150-d5b387d6-b9f1-4dc0-971f-ec357d9a42fd.mov

This was on Safari just now, but I have the same issue with Firefox.

**Comment by jben2021** [comment]
I just opened the Javascript console, and I'm getting:
[Error] Unhandled Promise Rejection: Error: recursive use of an object detected which would lead to unsafe aliasing in rust
	(anonymous function) (sseq_gui_wasm.js:336)
	wasm-stub
	<?>.wasm-function[1025]
	<?>.wasm-function[1027]
	<?>.wasm-function[746]
	wasm-stub
	746
	run (sseq_gui_wasm.js:225)
	(anonymous function) (resolution_worker.js:14)
	promiseReactionJob

**Comment by dalcde** [comment]
What firefox version are you on?

**Comment by jben2021** [comment]
96.0.3

**Comment by dalcde** [comment]
Can you try to perform the same action here and see what console output you get? https://dec41.user.srcf.net/tmp/test/sseq/

**Comment by jben2021** [comment]
The screen still goes blank, but now all I'm getting is a warning that "The Web Console logging API has been disabled by a script on this page." Sorry for the headache.

**Comment by dalcde** [comment]
Huh are you using any extensions?

**Comment by jben2021** [comment]
Actually I don't have a single extension...sorry for the headache. I'll also try setting up and using the non-web version over the next few days. Thanks for your help!

**Comment by jben2021** [comment]
I downloaded Rust and have been using the library on my own system this morning. I'm still getting issues with the custom module, but I'm seeing an error of "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: key must be a string at line 1 column 2', src/main.rs:84:57" when I try to resolve a custom module. For reference, I copied and pasted the first example in the Steenrod modules folder to make sure I wasn't doing something wrong.

**Comment by dalcde** [comment]
Can you run with the environment variable RUST_BACKTRACE=1 and paste the full backtrace?

**Comment by jben2021** [comment]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: key must be a string at line 1 column 2', src/main.rs:84:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: sseq_gui::Manager::new::{{closure}}
             at ./src/main.rs:84:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by jben2021** [comment]
So sorry for the mess. I talked with Eva Belmont, and she pointed out that in my "name" I was using \wedge. When I changed this to \\wedge, everything worked.

**Comment by jben2021** [comment]
Yeah, exactly. I had "name": "$C(2)\wedge C(2)$", and once I changed this to "name": "$C(2)\\wedge C(2)$" it was fine.
